name: Timeline
on: 
  [push]
  # workflow_run:
  #   workflows: ["CI build"]
  #   types:
  #     - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2
        # with: